version: '3'
services:
  lyceum_api:
    image: lyceum-api
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - "postgres"
    env_file:
      - .variables.env
    volumes:
      - "lyceum-images:/images"
    networks:
      front_net:
      default:

  postgres:
    image: postgres:12.12
    restart: always
    env_file:
      - .variables.env
    networks:
      default:
  test:
    build: ./test
    depends_on:
      - "lyceum_api"
    networks:
      default:

networks:
  front_net:
    external: true


volumes:
  lyceum-images:
