version: '3'
services:
  lyceum_api:
    image: lyceum-api
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - "postgres"
    env_file:
      - .variables.env
    networks:
      front_net:
      default:

  postgres:
    image: postgres:12.12
    restart: always
    env_file:
      - .variables.env
    ports:
      - "5432:5432"
    networks:
      default:

  nginx:
    image: nginx:stable
    restart: always
    networks:
      front_net:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config:/etc/nginx/conf.d:ro"
      - certbot-conf:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    command: "/bin/sh -c 'while :; do \
      sleep 6h & wait $${!}; nginx -s reload; \
      done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    restart: always
    networks:
      default:
    volumes:
      - certbot-conf:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do \
      certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  certbot-conf:
  certbot-webroot:


networks:
  front_net:
    external: true

